# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\git\Autoresuscitation\ccac_tools\ccac_form.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 810)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listView_files_to_copy = QtWidgets.QListView(self.centralwidget)
        self.listView_files_to_copy.setGeometry(QtCore.QRect(30, 30, 731, 192))
        self.listView_files_to_copy.setObjectName("listView_files_to_copy")
        self.listView_backup_locations = QtWidgets.QListView(self.centralwidget)
        self.listView_backup_locations.setGeometry(QtCore.QRect(30, 320, 731, 81))
        self.listView_backup_locations.setObjectName("listView_backup_locations")
        self.pushButton_add_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_files.setGeometry(QtCore.QRect(40, 230, 121, 51))
        self.pushButton_add_files.setObjectName("pushButton_add_files")
        self.pushButton_remove_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_files.setGeometry(QtCore.QRect(170, 230, 171, 51))
        self.pushButton_remove_files.setObjectName("pushButton_remove_files")
        self.pushButton_add_folder = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_add_folder.setGeometry(QtCore.QRect(40, 410, 121, 51))
        self.pushButton_add_folder.setObjectName("pushButton_add_folder")
        self.pushButton_remove_folders = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_remove_folders.setGeometry(QtCore.QRect(170, 410, 171, 51))
        self.pushButton_remove_folders.setObjectName("pushButton_remove_folders")
        self.label_files_to_copy = QtWidgets.QLabel(self.centralwidget)
        self.label_files_to_copy.setGeometry(QtCore.QRect(30, 10, 91, 16))
        self.label_files_to_copy.setObjectName("label_files_to_copy")
        self.label_backup_locations = QtWidgets.QLabel(self.centralwidget)
        self.label_backup_locations.setGeometry(QtCore.QRect(30, 300, 91, 16))
        self.label_backup_locations.setObjectName("label_backup_locations")
        self.pushButton_copy_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_copy_files.setGeometry(QtCore.QRect(40, 500, 121, 51))
        self.pushButton_copy_files.setObjectName("pushButton_copy_files")
        self.checkBox_clear_mode = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_clear_mode.setGeometry(QtCore.QRect(170, 500, 241, 17))
        self.checkBox_clear_mode.setObjectName("checkBox_clear_mode")
        self.pushButton_compare_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_compare_files.setGeometry(QtCore.QRect(450, 500, 121, 51))
        self.pushButton_compare_files.setObjectName("pushButton_compare_files")
        self.pushButton_clear_backed_up_files = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_clear_backed_up_files.setGeometry(QtCore.QRect(580, 500, 181, 51))
        self.pushButton_clear_backed_up_files.setObjectName("pushButton_clear_backed_up_files")
        self.textEdit_status = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_status.setGeometry(QtCore.QRect(40, 590, 721, 181))
        self.textEdit_status.setObjectName("textEdit_status")
        self.label_status = QtWidgets.QLabel(self.centralwidget)
        self.label_status.setGeometry(QtCore.QRect(50, 570, 91, 16))
        self.label_status.setObjectName("label_status")
        self.checkBox_delete_flag = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_delete_flag.setGeometry(QtCore.QRect(600, 480, 241, 17))
        self.checkBox_delete_flag.setObjectName("checkBox_delete_flag")
        self.spinBox_retry_limit = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox_retry_limit.setGeometry(QtCore.QRect(170, 530, 42, 22))
        self.spinBox_retry_limit.setProperty("value", 2)
        self.spinBox_retry_limit.setObjectName("spinBox_retry_limit")
        self.label_retry_limit = QtWidgets.QLabel(self.centralwidget)
        self.label_retry_limit.setGeometry(QtCore.QRect(220, 530, 221, 31))
        self.label_retry_limit.setObjectName("label_retry_limit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuRun = QtWidgets.QMenu(self.menubar)
        self.menuRun.setObjectName("menuRun")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionSelect_Append_Files = QtWidgets.QAction(MainWindow)
        self.actionSelect_Append_Files.setObjectName("actionSelect_Append_Files")
        self.actionClear_Files = QtWidgets.QAction(MainWindow)
        self.actionClear_Files.setObjectName("actionClear_Files")
        self.actionSelect_Append_Output_Folder_s = QtWidgets.QAction(MainWindow)
        self.actionSelect_Append_Output_Folder_s.setObjectName("actionSelect_Append_Output_Folder_s")
        self.actionClear_Output_Folders = QtWidgets.QAction(MainWindow)
        self.actionClear_Output_Folders.setObjectName("actionClear_Output_Folders")
        self.actionReset_Form = QtWidgets.QAction(MainWindow)
        self.actionReset_Form.setObjectName("actionReset_Form")
        self.actionCopy_and_Check = QtWidgets.QAction(MainWindow)
        self.actionCopy_and_Check.setObjectName("actionCopy_and_Check")
        self.actionCopy_Check_and_Clear = QtWidgets.QAction(MainWindow)
        self.actionCopy_Check_and_Clear.setObjectName("actionCopy_Check_and_Clear")
        self.actionCrawl_and_Compare_Tool = QtWidgets.QAction(MainWindow)
        self.actionCrawl_and_Compare_Tool.setObjectName("actionCrawl_and_Compare_Tool")
        self.menuHelp.addAction(self.actionAbout)
        self.menuFile.addAction(self.actionSelect_Append_Files)
        self.menuFile.addAction(self.actionClear_Files)
        self.menuFile.addAction(self.actionSelect_Append_Output_Folder_s)
        self.menuFile.addAction(self.actionClear_Output_Folders)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionReset_Form)
        self.menuRun.addAction(self.actionCopy_and_Check)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionCopy_Check_and_Clear)
        self.menuRun.addSeparator()
        self.menuRun.addAction(self.actionCrawl_and_Compare_Tool)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Copy Check and Clear Tools"))
        self.pushButton_add_files.setText(_translate("MainWindow", "Add Files"))
        self.pushButton_remove_files.setText(_translate("MainWindow", "Remove Selected Files"))
        self.pushButton_add_folder.setText(_translate("MainWindow", "Add Output Folder"))
        self.pushButton_remove_folders.setText(_translate("MainWindow", "Remove Selected Folders"))
        self.label_files_to_copy.setText(_translate("MainWindow", "Files to copy:"))
        self.label_backup_locations.setText(_translate("MainWindow", "Backup Locations:"))
        self.pushButton_copy_files.setText(_translate("MainWindow", "Copy Files"))
        self.checkBox_clear_mode.setText(_translate("MainWindow", "Automatically Clear Successfully Copied Files"))
        self.pushButton_compare_files.setText(_translate("MainWindow", "Compare Files"))
        self.pushButton_clear_backed_up_files.setText(_translate("MainWindow", "Clear Successfully Backed-up Files"))
        self.label_status.setText(_translate("MainWindow", "Status:"))
        self.checkBox_delete_flag.setText(_translate("MainWindow", "Enable Clearing"))
        self.label_retry_limit.setText(_translate("MainWindow", "File copying RETRY limit\n"
"[0] don\'t retry, [2] retry 2 times if needed"))
        self.menuHelp.setTitle(_translate("MainWindow", "Help"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuRun.setTitle(_translate("MainWindow", "Run"))
        self.actionAbout.setText(_translate("MainWindow", "About"))
        self.actionSelect_Append_Files.setText(_translate("MainWindow", "Select/Append File(s)"))
        self.actionClear_Files.setText(_translate("MainWindow", "Clear Files"))
        self.actionSelect_Append_Output_Folder_s.setText(_translate("MainWindow", "Select/Append Output Folder(s)"))
        self.actionClear_Output_Folders.setText(_translate("MainWindow", "Clear Output Folders"))
        self.actionReset_Form.setText(_translate("MainWindow", "Reset Form"))
        self.actionCopy_and_Check.setText(_translate("MainWindow", "Copy and Check"))
        self.actionCopy_Check_and_Clear.setText(_translate("MainWindow", "Copy, Check, and Clear"))
        self.actionCrawl_and_Compare_Tool.setText(_translate("MainWindow", "Crawl and Compare Tool"))

